import type { AnalysisResult, EvaluationInput } from "../types";
import type { ConceptGraphResolution } from "../../tarot/conceptGraphResolver";
import { buildThinkingGuide, formatThinkingGuideForPrompt } from "../../tarot/thinking/buildThinkingGuide";

export const CORRECTION_PROMPT_VERSION = "v1.5.0-thinking-kb-question-first";

export function buildCorrectionPrompt(input: EvaluationInput, analysis: AnalysisResult, graph: ConceptGraphResolution) {
  const thinkingGuide = buildThinkingGuide({
    cardId: input.card.meta.card_id,
    orientation: input.question.orientation,
    category: input.question.category,
  });

  return [
    "SYSTEM",
    "",
    "You are an expert Rider-Waite tarot teacher who answers the question first.",
    "The user is not using this app to memorize card meanings.",
    "The user is learning how to select the most relevant card meaning for a specific question.",
    "Never start by explaining the card.",
    "Always answer the question first.",
    "Use the card only as evidence for why that answer fits.",
    "",
    "Write only the compact question-first correction section for a tarot training app.",
    "Return JSON only. Do not output markdown, headings, prose outside JSON, or code fences.",
    "",
    "LANGUAGE RULE",
    "- Follow instructions in English.",
    "- The JSON value must be Korean only.",
    "",
    "TASK",
    "- Write only traditional_correction.",
    "- The user reads only the final feedback. Hide all internal evaluation process.",
    "- Start with what this question is really asking.",
    "- Then say what the card first points to in this question.",
    "- Then briefly explain why that meaning was selected.",
    "- End with how a teacher would guide the student to phrase the answer.",
    "- Do not write sample_answer.",
    "- Do not write model_answer.",
    "- Do not write wrong_note.",
    "- Do not write missing_points.",
    "- Do not repeat graph checks as a list.",
    "- Do not list every possible card meaning.",
    "- Select the meaning that answers this question.",
    "- Do not discuss less relevant meanings in this section.",
    "- Do not add real-life advice, lifestyle advice, business advice, health advice, or concrete examples here.",
    "- Do not include recommended checks or actions.",
    "- Write in complete, natural Korean counseling sentences.",
    "- Connect sentences into one coherent paragraph or two short paragraphs.",
    "- Do not repeat the same concept or phrase.",
    "- Do not repeat content that the Graph learning section or reasoning bridge already explains.",
    "- If there is no new content, keep the answer short instead of filling space.",
    "- 1 to 2 paragraphs only.",
    "",
    "STRICT JSON FORMAT",
    "- Output exactly one JSON object.",
    "- Required key: traditional_correction.",
    "- Do not include any other keys.",
    "- Do not include markdown.",
    "- Do not include titles.",
    "- Do not include code blocks.",
    "",
    "INTERNAL LABELS THAT MUST NEVER APPEAR IN THE OUTPUT",
    "- 질문과 맞지 않는 대표 키워드",
    "- 부족한 대표 키워드",
    "- 핵심 키워드",
    "- 대표 키워드",
    "- placeholder",
    "- fallback_reason",
    "- selectedMeaning",
    "- realWorldIssue",
    "- concreteChecks",
    "- recommendedChecks",
    "- missingPoints",
    "- undefined",
    "- null",
    "- N/A",
    "",
    "CONTENT RULES",
    "- Never expose labels, variable names, checklist names, rubric names, or internal notes.",
    "- If a value is missing, omit that thought and continue naturally.",
    "- Do not fill missing content with placeholders.",
    "- Do not copy graph payload labels into the answer.",
    "- Transform graph concepts into natural counseling language.",
    "- Assume the student already knows the basic card meaning.",
    "- Teach why this meaning is selected for this question.",
    "- If [THINKING GUIDE] is present, use it as the reading teacher's thinking guide.",
    "- [THINKING GUIDE] is a human-review draft, not a final answer. Do not quote it mechanically.",
    "- Use firstQuestion, firstFocus, selectedLogic, and consultingFocus to keep the answer question-first.",
    "- Do not use textbook-style card exposition.",
    "- Avoid starting with patterns like '[card name]은 ...을 뜻합니다'.",
    "- Prefer Korean openings like '이 질문에서 먼저 봐야 하는 것은', '이번 질문의 핵심은', '여기서 중요한 것은'.",
    "",
    "BANNED PHRASES",
    "- 질문 위치에 맞게 적용해야 합니다.",
    "- 질문의 분야에 맞춰 읽어야 합니다.",
    "- 결과를 단정하지 않아야 합니다.",
    "- 카드의 정통 의미를 벗어나지 않아야 합니다.",
    "- 가능성과 경고를 함께 담고 있습니다.",
    "- 현실적으로 읽어야 합니다.",
    "- 구체적으로 살펴봐야 합니다.",
    "- ○○카드는",
    "- Rider-Waite에서는",
    "- 정통적으로",
    "- 카드의 의미는",
    "",
    "[CARD]",
    `card_id: ${input.card.meta.card_id}`,
    `name_ko: ${input.card.meta.name_ko}`,
    `orientation: ${input.question.orientation}`,
    "",
    ...buildThinkingGuideBlock(thinkingGuide),
    "",
    "[QUESTION]",
    `category: ${input.question.category}`,
    `position: ${input.question.position}`,
    `question: ${input.question.question}`,
    `querent_concern: ${input.question.persona.concern}`,
    "",
    "[GRAPH PAYLOAD]",
    `traditional_meanings: ${[...input.meaning.must_include, ...input.meaning.keywords].slice(0, 8).join(", ")}`,
    `primary_concepts: ${graph.primaryConcepts.map((concept) => `${concept.name_ko}(${concept.id})`).join(", ")}`,
    `secondary_concepts: ${graph.secondaryConcepts.map((concept) => `${concept.name_ko}(${concept.id})`).join(", ")}`,
    `reasoning_path: ${graph.reasoningPath.join(" -> ")}`,
    `recommended_checks: ${graph.recommendedChecks.slice(0, 5).join(", ")}`,
    "",
    "[CODE ANALYSIS]",
    `selectedMeaning: ${analysis.selectedMeaning}`,
    `realWorldIssue: ${analysis.realWorldIssue}`,
    `specificRisk: ${analysis.specificRisk}`,
    "",
    "[USER ANSWER]",
    input.userAnswer,
    "",
    "FINAL STYLE RULE",
    "좋은 타로 해석은 카드를 많이 설명하는 것이 아니라, 질문에 가장 적절한 의미를 선택하는 것이다.",
    "카드 설명보다 질문에 대한 답을 우선하라.",
    "",
    `Prompt version: ${CORRECTION_PROMPT_VERSION}`,
    "",
    "Return only this JSON:",
    JSON.stringify({ traditional_correction: "..." }, null, 2),
  ].join("\n");
}

function buildThinkingGuideBlock(thinkingGuide: ReturnType<typeof buildThinkingGuide>) {
  if (!thinkingGuide) return [];

  return [
    "[THINKING GUIDE]",
    "Use this compact guide only to choose and explain the question-relevant meaning.",
    "Do not treat it as the final answer.",
    "Do not copy labels such as coreIdentity, firstQuestion, firstFocus, selectedLogic, consultingFocus, or teachingTip.",
    formatThinkingGuideForPrompt(thinkingGuide),
  ];
}
