import type { AnalysisResult, EvaluationInput } from "../types";
import type { ConceptGraphResolution } from "../../tarot/conceptGraphResolver";

export const CORRECTION_PROMPT_VERSION = "v1.3.0-compact-traditional-correction";

export function buildCorrectionPrompt(input: EvaluationInput, analysis: AnalysisResult, graph: ConceptGraphResolution) {
  return [
    "SYSTEM",
    "",
    "You are an expert Rider-Waite tarot teacher.",
    "Write only the traditional correction section for a tarot training app.",
    "Return JSON only. Do not output markdown, headings, prose outside JSON, or code fences.",
    "",
    "LANGUAGE RULE",
    "- Follow instructions in English.",
    "- The JSON value must be Korean only.",
    "",
    "TASK",
    "- Write only traditional_correction.",
    "- The user reads only the final feedback. Hide all internal evaluation process.",
    "- Do not write sample_answer.",
    "- Do not write model_answer.",
    "- Do not write wrong_note.",
    "- Do not write missing_points.",
    "- Do not repeat graph checks as a list.",
    "- Explain only the card's traditional meaning and how the question focus selects one meaning.",
    "- Do not list every possible card meaning. Select the meaning that answers this question.",
    "- Do not discuss less relevant meanings in this section.",
    "- Do not add real-life advice, lifestyle advice, business advice, health advice, or concrete examples here.",
    "- Do not include recommended checks or actions.",
    "- Write in complete, natural Korean counseling sentences.",
    "- Connect sentences into one coherent paragraph or two short paragraphs.",
    "- Do not repeat the same concept or phrase.",
    "- Do not repeat content that the Graph learning section or reasoning bridge already explains.",
    "- If there is no new content, keep the answer short instead of filling space.",
    "- 1 to 2 paragraphs only.",
    "",
    "STRICT JSON FORMAT",
    "- Output exactly one JSON object.",
    "- Required key: traditional_correction.",
    "- Do not include any other keys.",
    "- Do not include markdown.",
    "- Do not include titles.",
    "- Do not include code blocks.",
    "",
    "INTERNAL LABELS THAT MUST NEVER APPEAR IN THE OUTPUT",
    "- 질문과 맞지 않는 대표 키워드",
    "- 부족한 대표 키워드",
    "- 핵심 키워드",
    "- 대표 키워드",
    "- placeholder",
    "- fallback_reason",
    "- selectedMeaning",
    "- realWorldIssue",
    "- concreteChecks",
    "- recommendedChecks",
    "- missingPoints",
    "- undefined",
    "- null",
    "- N/A",
    "",
    "CONTENT RULES",
    "- Never expose labels, variable names, checklist names, rubric names, or internal notes.",
    "- If a value is missing, omit that thought and continue naturally.",
    "- Do not fill missing content with placeholders.",
    "- Do not copy graph payload labels into the answer.",
    "- Transform graph concepts into natural counseling language.",
    "- Start from the card's traditional meaning.",
    "- End after explaining which meaning is applied to this question.",
    "- Do not write a counseling sentence in this section.",
    "",
    "BANNED PHRASES",
    "- 질문 위치에 맞게 적용해야 합니다.",
    "- 질문의 분야에 맞춰 읽어야 합니다.",
    "- 결과를 단정하지 않아야 합니다.",
    "- 카드의 정통 의미를 벗어나지 않아야 합니다.",
    "- 가능성과 경고를 함께 담고 있습니다.",
    "- 현실적으로 읽어야 합니다.",
    "- 구체적으로 살펴봐야 합니다.",
    "",
    "[CARD]",
    `card_id: ${input.card.meta.card_id}`,
    `name_ko: ${input.card.meta.name_ko}`,
    `orientation: ${input.question.orientation}`,
    "",
    "[QUESTION]",
    `category: ${input.question.category}`,
    `position: ${input.question.position}`,
    `question: ${input.question.question}`,
    "",
    "[GRAPH PAYLOAD]",
    `traditional_meanings: ${[...input.meaning.must_include, ...input.meaning.keywords].slice(0, 8).join(", ")}`,
    `primary_concepts: ${graph.primaryConcepts.map((concept) => `${concept.name_ko}(${concept.id})`).join(", ")}`,
    `secondary_concepts: ${graph.secondaryConcepts.map((concept) => `${concept.name_ko}(${concept.id})`).join(", ")}`,
    `reasoning_path: ${graph.reasoningPath.join(" -> ")}`,
    `recommended_checks: ${graph.recommendedChecks.slice(0, 5).join(", ")}`,
    "",
    "[CODE ANALYSIS]",
    `selectedMeaning: ${analysis.selectedMeaning}`,
    `realWorldIssue: ${analysis.realWorldIssue}`,
    `specificRisk: ${analysis.specificRisk}`,
    "",
    "[USER ANSWER]",
    input.userAnswer,
    "",
    `Prompt version: ${CORRECTION_PROMPT_VERSION}`,
    "",
    "Return only this JSON:",
    JSON.stringify({ traditional_correction: "..." }, null, 2),
  ].join("\n");
}
