import type { AnalysisResult, EvaluationInput } from "../types";

export const PROMPT_VERSION = "v3.0.0";
export const ANALYSIS_PROMPT_VERSION = PROMPT_VERSION;
export const FEEDBACK_PROMPT_VERSION = PROMPT_VERSION;

export function buildAnalysisPrompt({ card, meaning, question, userAnswer }: EvaluationInput) {
  const contextText = getContextText({ card, question });

  return [
    "너는 Rider-Waite 전통 타로 답변을 채점하는 분석 엔진이다.",
    "",
    "역할",
    "",
    "사용자의 답변을 분석하여 최종 피드백에 사용할 JSON만 생성한다.",
    "",
    "절대로 상담하거나 설명하지 않는다.",
    "",
    "반드시 JSON만 반환한다.",
    "",
    "Markdown 금지.",
    "코드블럭 금지.",
    "설명문 금지.",
    "",
    "채점 기준",
    "",
    "- 카드의 정통 의미를 이해했는가",
    "- 질문 위치에 맞게 적용했는가",
    "- 과하게 단정하지 않았는가",
    "- 카드 상징을 활용했는가",
    "",
    "중요 규칙",
    "",
    "- 질문 위치를 반드시 고려한다.",
    "- 카드의 범용 의미를 그대로 쓰지 않는다.",
    "- 질문에 맞게 변환한다.",
    "- 억지 칭찬을 만들지 않는다.",
    "- 맞은 내용이 없으면 빈 배열을 반환한다.",
    "- 질문과 관계없는 해석은 avoid_topics에 넣는다.",
    "",
    `Prompt version: ${ANALYSIS_PROMPT_VERSION}`,
    "",
    "[카드 정보]",
    `card_id: ${card.meta.card_id}`,
    `name_ko: ${card.meta.name_ko}`,
    `name_en: ${card.meta.name_en}`,
    `arcana: ${card.meta.arcana}`,
    `suit: ${card.meta.suit ?? "major"}`,
    `orientation: ${question.orientation}`,
    "",
    "[정통 의미 데이터]",
    `keywords: ${meaning.keywords.join(", ")}`,
    `traditional_meaning: ${meaning.traditional_meaning}`,
    `positive_aspect: ${meaning.positive_aspect}`,
    `warning: ${meaning.warning}`,
    `must_include: ${meaning.must_include.join(", ")}`,
    `common_mistakes: ${meaning.common_mistakes.join(", ")}`,
    `symbolism: ${(meaning.symbolism ?? []).join(", ")}`,
    "",
    "[질문]",
    `category: ${question.category}`,
    `position: ${question.position}`,
    `question: ${question.question}`,
    `persona_age: ${question.persona.age}`,
    `persona_background: ${question.persona.background}`,
    `persona_concern: ${question.persona.concern}`,
    `context_for_category: ${contextText}`,
    "",
    "[사용자 답변]",
    userAnswer,
    "",
    "JSON Schema",
    JSON.stringify(
      {
        score: 82,
        grade: "partial",
        rubric: {
          traditionalMeaning: 4,
          questionApplication: 4,
          symbolAwareness: 3,
          overstatementControl: 4,
        },
        specific_strengths: [],
        specific_improvements: [],
        missed_core_points: [],
        incorrect_points: [],
        traditional_core: "",
        contextual_meaning: "",
        symbol_notes: [],
        feedback_focus: "",
        sample_answer_draft: "",
        model_answer_draft: "",
        difference_notes: [],
        correction_note: "",
        missed_key_points: [],
        avoid_topics: [],
      },
      null,
      2,
    ),
    "",
    "필드 규칙",
    "",
    "specific_strengths",
    "→ 사용자가 실제 맞힌 카드 의미만 작성",
    "",
    "specific_improvements",
    "→ 사용자가 놓친 카드 의미만 작성",
    "",
    "missed_core_points",
    "→ 가장 중요한 핵심만 작성",
    "",
    "incorrect_points",
    "→ 정통 의미와 다르게 읽은 부분만 작성",
    "",
    "traditional_core",
    "→ 카드 자체의 정통 의미",
    "",
    "contextual_meaning",
    "→ 질문 위치에서의 의미",
    "",
    "symbol_notes",
    "→ 카드 이미지 근거",
    "",
    "feedback_focus",
    "→ 이번 피드백에서 가장 강조할 핵심 1개",
    "",
    "sample_answer_draft",
    "→ 내담자에게 말하는 상담 예시 (2~3문장)",
    "",
    "model_answer_draft",
    "→ 수강생이 제출할 모범 답안 (2~3문장)",
    "",
    "difference_notes",
    "→ 사용자 답변과 정통 해석의 차이",
    "",
    "correction_note",
    "→ 아래 순서를 반드시 따른다.",
    "",
    "1. 사용자가 어떻게 읽었는가",
    "2. 무엇이 부족했는가",
    "3. 다음에는 어떻게 읽는가",
    "",
    "missed_key_points",
    "→ ☑ 맞은 핵심 / ☐ 놓친 핵심",
    "",
    "avoid_topics",
    "→ 질문과 관계없는 범용 해석",
  ].join("\n");
}

export function buildFeedbackPrompt(input: EvaluationInput, analysis: AnalysisResult) {
  const { card, question, userAnswer } = input;

  return [
    "너는 타로 강사가 아니다.",
    "",
    "너는 Analysis JSON을 사용자에게 보여줄 형태로 정리하는 편집자다.",
    "",
    "새로운 해석을 만들지 않는다.",
    "",
    "Analysis JSON만 사용한다.",
    "",
    "Analysis JSON에 없는 내용을 추가하지 않는다.",
    "",
    "같은 의미를 반복하지 않는다.",
    "",
    "반드시 JSON만 반환한다.",
    "",
    "Markdown 금지.",
    "",
    "코드블럭 금지.",
    "",
    "설명문 금지.",
    "",
    "--------------------------------------------------",
    "",
    "문체 규칙",
    "",
    '- 모든 문장은 "-합니다." 체를 사용한다.',
    "- 짧고 명확하게 작성한다.",
    "- 교재처럼 설명한다.",
    "- 접속사를 최소화한다.",
    "- 감성적인 표현을 사용하지 않는다.",
    "- 상담사처럼 위로하지 않는다.",
    "- 같은 의미를 두 번 설명하지 않는다.",
    "",
    "권장 표현",
    "",
    "- ~입니다.",
    "- ~를 의미합니다.",
    "- ~가 핵심입니다.",
    "- ~를 먼저 봅니다.",
    "- ~로 해석합니다.",
    "- ~에 가깝습니다.",
    "- ~를 놓쳤습니다.",
    "- ~를 함께 봐야 합니다.",
    "",
    "금지 표현",
    "",
    "- 좋아 보입니다.",
    "- 느껴집니다.",
    "- 가능성이 있습니다.",
    "- 생각해볼 필요가 있습니다.",
    "- 조금 더 구체적으로.",
    "- 상담에서는.",
    "- 현실에서는.",
    "- 카드의 일부 흐름은 잡았습니다.",
    "- 질문 위치에 맞게 적용해야 합니다.",
    "",
    "--------------------------------------------------",
    "",
    "출력 규칙",
    "",
    "strengths",
    "→ analysis.specific_strengths",
    "",
    "missing_points",
    "→ analysis.specific_improvements",
    "",
    "traditional_correction",
    "↓",
    "① 질문 위치",
    "analysis.contextual_meaning",
    "↓",
    "② 정통 의미",
    "analysis.traditional_core",
    "↓",
    "③ 상징 근거",
    "analysis.symbol_notes",
    "",
    "sample_answer",
    "→ analysis.sample_answer_draft",
    "",
    "model_answer",
    "→ analysis.model_answer_draft",
    "",
    "missed_key_points",
    "→ analysis.missed_key_points",
    "",
    "differences",
    "→ analysis.difference_notes",
    "",
    "wrong_note",
    "→ analysis.correction_note",
    "",
    "next_reading_tip",
    "→ analysis.feedback_focus",
    "",
    "--------------------------------------------------",
    "",
    "빈 배열 처리",
    "",
    "specific_strengths가 비어있으면",
    '"정통 의미를 정확히 짚은 부분은 아직 부족합니다."',
    "",
    "specific_improvements가 비어있으면",
    '"큰 보완점은 없습니다."',
    "",
    `Prompt version: ${FEEDBACK_PROMPT_VERSION}`,
    "",
    "[문맥 확인용 정보]",
    `card: ${card.meta.name_ko} / ${card.meta.name_en}`,
    `orientation: ${question.orientation}`,
    `category: ${question.category}`,
    `position: ${question.position}`,
    `question: ${question.question}`,
    `persona_background: ${question.persona.background}`,
    `persona_concern: ${question.persona.concern}`,
    "",
    "[사용자 답변]",
    userAnswer,
    "",
    "[Analysis JSON]",
    JSON.stringify(analysis, null, 2),
    "",
    "최종 JSON Schema",
    JSON.stringify(
      {
        score: analysis.score,
        grade: analysis.grade,
        rubric: {
          traditionalMeaning: analysis.rubric.traditionalMeaning,
          questionApplication: analysis.rubric.questionApplication,
          counselingExpression: analysis.rubric.symbolAwareness,
          practicalApplication: analysis.rubric.questionApplication,
          certaintyControl: analysis.rubric.overstatementControl,
        },
        strengths: analysis.specific_strengths.length > 0 ? analysis.specific_strengths : ["정통 의미를 정확히 짚은 부분은 아직 부족합니다."],
        missing_points: analysis.specific_improvements.length > 0 ? analysis.specific_improvements : ["큰 보완점은 없습니다."],
        traditional_correction: `① 질문 위치\n${analysis.contextual_meaning}\n\n② 정통 의미\n${analysis.traditional_core}\n\n③ 상징 근거\n${analysis.symbol_notes.join(" ")}`,
        sample_answer: analysis.sample_answer_draft,
        model_answer: analysis.model_answer_draft,
        missed_key_points: analysis.missed_key_points,
        differences: analysis.difference_notes,
        wrong_note: analysis.correction_note,
        next_reading_tip: analysis.feedback_focus,
        promptVersion: FEEDBACK_PROMPT_VERSION,
      },
      null,
      2,
    ),
  ].join("\n");
}

function getContextText({ card, question }: Pick<EvaluationInput, "card" | "question">) {
  const contexts = card.contexts;
  if (!contexts) return "";

  if (
    question.category === "love" ||
    question.category === "reunion" ||
    question.category === "career" ||
    question.category === "business" ||
    question.category === "money" ||
    question.category === "health"
  ) {
    return contexts[question.category]?.[question.orientation] ?? "";
  }

  return "";
}
