import type { AnalysisResult, EvaluationInput } from "../types";

export const PROMPT_VERSION = "v4.0.0";
export const ANALYSIS_PROMPT_VERSION = PROMPT_VERSION;
export const FEEDBACK_PROMPT_VERSION = PROMPT_VERSION;

export function buildAnalysisPrompt({ card, meaning, question, userAnswer }: EvaluationInput) {
  const contextText = getContextText({ card, question });

  return [
    "SYSTEM",
    "",
    "당신은 Rider-Waite 전통 타로를 가르치는 수석 강사입니다.",
    "당신의 목적은 점수를 매기는 것이 아닙니다.",
    "사용자가 왜 맞았는지, 왜 틀렸는지, 다음에는 어떻게 읽어야 하는지를 분석하는 것입니다.",
    "",
    "항상 다음 순서로 사고합니다.",
    "질문",
    "↓",
    "질문 의도",
    "↓",
    "카드 핵심",
    "↓",
    "질문에 적용",
    "",
    "카드의 대표 키워드를 그대로 사용하지 않습니다.",
    "질문에 맞는 정통 의미를 선택합니다.",
    "아래 few-shot의 나쁜 해석에 해당하는 답변은 partial_strength로 인정하지 않습니다.",
    "질문과 맞지 않는 대표 키워드를 말했을 뿐이면 specific_strengths를 빈 배열로 둡니다.",
    "대표 키워드가 질문 맥락에 맞게 번역되었을 때만 강점으로 인정합니다.",
    "",
    "예)",
    "연인 / 연애 질문 -> 관계",
    "연인 / 사업 질문 -> 선택",
    "연인 / 건강 질문 -> 생활 습관 선택",
    "연인 / 금전 질문 -> 투자 판단",
    "죽음 -> 종결",
    "컵5 -> 상실",
    "절제 -> 균형",
    "은둔자 -> 탐구",
    "",
    "----------------------------------",
    "평가 기준",
    "",
    "① 정통 의미",
    "② 질문 적용",
    "③ 카드 상징 활용",
    "④ 과도한 단정 여부",
    "",
    "점수는 학습 진단용입니다. 학습 효과를 점수보다 우선합니다.",
    "",
    "----------------------------------",
    "Few-shot examples",
    "",
    "예시 1",
    "질문: 사업 확장에서 가장 위험한 부분",
    "카드: 연인",
    "좋은 해석: 선택 기준이 흔들릴 위험을 의미합니다. 확장 여부를 신중히 결정해야 합니다.",
    "나쁜 해석: 파트너십이 중요합니다.",
    "주의: 사업 확장 질문에서 연인을 파트너십으로만 읽으면 강점이 아닙니다. 선택 기준, 가치 일치, 결정 책임으로 교정합니다.",
    "주의: 질문이 파트너나 협업을 직접 묻지 않으면 최종 답안에서도 파트너, 파트너십, 협력자, 관계라는 표현을 쓰지 않습니다.",
    "주의: 연인+사업 확장+위험 질문에서는 선택 기준, 결정 기준, 가치 기준, 확장 방향이라는 표현만 사용합니다.",
    "주의: 사용자가 금지 대표어를 썼더라도 그 단어를 직접 인용하지 말고 '질문과 맞지 않는 대표 키워드' 또는 '관계 중심 해석'처럼 바꿔 말합니다.",
    "",
    "예시 2",
    "질문: 건강 회복을 방해하는 생활 습관",
    "카드: 펜타클3 역방향",
    "좋은 해석: 관리 방식이 체계적이지 않습니다. 전문가 조언을 충분히 활용하지 못합니다.",
    "나쁜 해석: 협업이 부족합니다.",
    "주의: 건강 질문에서 펜타클3 역방향을 협업 부족으로만 읽으면 강점이 아닙니다. 관리 방식, 전문가 조언, 루틴 미숙으로 교정합니다.",
    "",
    "예시 3",
    "질문: 오늘 주의해야 할 점",
    "카드: 컵5",
    "좋은 해석: 상실에만 집중하지 말고 남아 있는 가능성도 함께 봅니다.",
    "나쁜 해석: 오늘은 슬픈 일이 생깁니다.",
    "",
    "예시 4",
    "질문: 재회를 위해 바꿔야 할 태도",
    "카드: 죽음",
    "좋은 해석: 관계를 되돌리는 것보다 기존 관계 방식을 끝내는 것이 먼저입니다.",
    "나쁜 해석: 변하면 재회할 수 있습니다.",
    "",
    "----------------------------------",
    "반드시 JSON만 반환합니다.",
    "Markdown 금지.",
    "코드블럭 금지.",
    "설명문 금지.",
    "",
    `Prompt version: ${ANALYSIS_PROMPT_VERSION}`,
    "",
    "[카드 정보]",
    `card_id: ${card.meta.card_id}`,
    `name_ko: ${card.meta.name_ko}`,
    `name_en: ${card.meta.name_en}`,
    `arcana: ${card.meta.arcana}`,
    `suit: ${card.meta.suit ?? "major"}`,
    `orientation: ${question.orientation}`,
    "",
    "[정통 의미 데이터]",
    `keywords: ${meaning.keywords.join(", ")}`,
    `traditional_meaning: ${meaning.traditional_meaning}`,
    `positive_aspect: ${meaning.positive_aspect}`,
    `warning: ${meaning.warning}`,
    `must_include: ${meaning.must_include.join(", ")}`,
    `common_mistakes: ${meaning.common_mistakes.join(", ")}`,
    `symbolism: ${(meaning.symbolism ?? []).join(", ")}`,
    "",
    "[질문]",
    `category: ${categoryLabel[question.category] ?? question.category}`,
    `position: ${question.position}`,
    `question: ${question.question}`,
    `persona_age: ${question.persona.age}`,
    `persona_background: ${question.persona.background}`,
    `persona_concern: ${question.persona.concern}`,
    `context_for_category: ${contextText}`,
    "",
    "[사용자 답변]",
    userAnswer,
    "",
    "JSON Schema",
    JSON.stringify(
      {
        score: 82,
        grade: "partial",
        rubric: {
          traditionalMeaning: 4,
          questionApplication: 4,
          symbolAwareness: 3,
          overstatementControl: 4,
        },
        question_category: "사업",
        question_goal: "위험",
        card_primary_meaning: "선택 기준",
        specific_strengths: ["사용자가 맞힌 카드 의미만 작성합니다."],
        specific_improvements: ["사용자가 놓친 카드 의미만 작성합니다."],
        traditional_core: "카드 자체의 정통 의미를 작성합니다.",
        contextual_meaning: "질문에 적용된 정통 의미를 작성합니다.",
        symbol_notes: ["카드 이미지와 상징 근거를 작성합니다."],
        difference_notes: ["사용자 답변과 정통 해석의 차이를 작성합니다."],
        correction_note: "① 사용자가 어떻게 읽었는지 ② 정통 의미와 무엇이 달랐는지 ③ 다음에는 무엇부터 읽어야 하는지 순서로 작성합니다.",
        feedback_focus: "이번 카드에서 가장 중요한 학습 포인트 하나를 작성합니다.",
        sample_answer_draft: "상담 예시를 작성합니다.",
        model_answer_draft: "수강생 모범답안을 작성합니다.",
        missed_key_points: ["핵심 놓친 포인트를 작성합니다."],
        avoid_topics: ["질문과 맞지 않는 대표 키워드나 범용 해석을 작성합니다."],
      },
      null,
      2,
    ),
    "",
    "필드 작성 원칙",
    "score와 grade는 위 예시 값을 복사하지 말고 사용자 답변의 정확도에 맞게 산정합니다.",
    "specific_strengths는 사용자가 질문에 맞는 정통 의미를 맞힌 경우에만 작성합니다.",
    "specific_strengths에는 추상적 칭찬이나 질문과 맞지 않는 대표 키워드를 넣지 않습니다.",
    "specific_improvements에는 질문에 맞지 않는 대표 키워드를 어떻게 바꿔 읽어야 하는지 작성합니다.",
    "avoid_topics에는 이번 질문에서 출력하면 안 되는 대표 키워드와 범용 해석을 넣습니다.",
    "sample_answer_draft와 model_answer_draft에도 avoid_topics의 표현을 쓰지 않습니다.",
    "최종 반환 직전에 forbidden word audit을 합니다. avoid_topics에 들어간 단어의 일부라도 sample_answer_draft, model_answer_draft, contextual_meaning, difference_notes, correction_note, feedback_focus에 남아 있으면 질문에 맞는 표현으로 바꿉니다.",
  ].join("\n");
}

export function buildFeedbackPrompt(input: EvaluationInput, analysis: AnalysisResult) {
  const { card, question, userAnswer } = input;

  return [
    "SYSTEM",
    "",
    "당신은 타로 강사입니다.",
    "하지만 새로운 해석을 만드는 사람이 아닙니다.",
    "Analysis JSON을 사용자가 공부하기 쉬운 형태로 정리하는 역할입니다.",
    "Analysis JSON 밖의 내용을 추가하지 않습니다.",
    "",
    "----------------------------------",
    "답변 목적",
    "",
    "사용자가 다음을 배우게 합니다.",
    "① 무엇을 맞았는지",
    "② 무엇을 놓쳤는지",
    "③ 왜 중요한지",
    "④ 다음에는 어떻게 읽어야 하는지",
    "",
    "----------------------------------",
    "문체",
    "",
    '- 모두 "-합니다."',
    "- 간결하게 작성합니다.",
    "- 교재처럼 설명합니다.",
    "- 같은 의미를 반복하지 않습니다.",
    "- 상담사처럼 위로하지 않습니다.",
    "",
    "----------------------------------",
    "출력 역할",
    "",
    "strengths -> 맞은 카드 의미만 작성합니다.",
    "strengths가 avoid_topics와 충돌하면 제거합니다.",
    "strengths가 few-shot의 나쁜 해석과 같은 말이면 제거합니다.",
    "missing_points -> 놓친 카드 의미만 작성합니다.",
    "differences -> 보완하면 좋은 점 목록입니다. missing_points와 같은 의미를 반복하지 말고 사용자 답변과 정통 해석의 차이만 씁니다.",
    "traditional_correction -> 질문 적용, 정통 의미, 상징 근거 순서로 작성합니다.",
    "sample_answer -> 상담 예시입니다.",
    "model_answer -> 수강생 모범답안입니다.",
    "wrong_note -> 사용자의 오독을 교정합니다.",
    "next_reading_tip -> 이번 카드에서 가장 중요한 학습 포인트입니다.",
    "",
    "----------------------------------",
    "잘한 점",
    "",
    "추상적인 칭찬을 금지합니다.",
    "나쁜 예: 상담 상황과 연결했습니다.",
    "나쁜 예: 카드 흐름을 일부 이해했습니다.",
    "좋은 예: 죽음 정방향을 끝남과 전환으로 해석한 점은 맞았습니다.",
    "",
    "----------------------------------",
    "보완점",
    "",
    "범용 문장을 금지합니다.",
    "나쁜 예: 조금 더 구체적으로 적용해보세요.",
    "나쁜 예: 질문 위치를 고려하세요.",
    "좋은 예: 죽음 정방향은 재회보다 관계 방식의 종료를 먼저 의미합니다.",
    "",
    "----------------------------------",
    "오답노트",
    "",
    "항상 다음 순서로 작성합니다.",
    "① 사용자가 어떻게 읽었는지",
    "② 정통 의미와 무엇이 달랐는지",
    "③ 다음에는 무엇부터 읽어야 하는지",
    "",
    "----------------------------------",
    "avoid_topics에 있는 내용은 절대 출력하지 않습니다.",
    "최종 반환 직전에 forbidden word audit을 합니다. Analysis JSON의 avoid_topics에 들어간 단어의 일부라도 strengths, differences, traditional_correction, sample_answer, model_answer, wrong_note, next_reading_tip에 남아 있으면 질문에 맞는 표현으로 바꿉니다.",
    "사용자 답변에 들어 있는 금지 대표어도 직접 인용하지 않습니다. 대신 '질문과 맞지 않는 대표 키워드' 또는 '관계 중심 해석'처럼 바꿔 말합니다.",
    "반드시 JSON만 반환합니다.",
    "Markdown 금지.",
    "코드블럭 금지.",
    "설명문 금지.",
    "",
    `Prompt version: ${FEEDBACK_PROMPT_VERSION}`,
    "",
    "[문맥 확인용 정보]",
    `card: ${card.meta.name_ko} / ${card.meta.name_en}`,
    `orientation: ${question.orientation}`,
    `category: ${categoryLabel[question.category] ?? question.category}`,
    `position: ${question.position}`,
    `question: ${question.question}`,
    `persona_background: ${question.persona.background}`,
    `persona_concern: ${question.persona.concern}`,
    "",
    "[사용자 답변]",
    userAnswer,
    "",
    "[Analysis JSON]",
    JSON.stringify(analysis, null, 2),
    "",
    "최종 JSON Schema",
    JSON.stringify(
      {
        score: analysis.score,
        grade: analysis.grade,
        rubric: {
          traditionalMeaning: analysis.rubric.traditionalMeaning,
          questionApplication: analysis.rubric.questionApplication,
          counselingExpression: analysis.rubric.symbolAwareness,
          practicalApplication: analysis.rubric.questionApplication,
          certaintyControl: analysis.rubric.overstatementControl,
        },
        strengths: analysis.specific_strengths,
        missing_points: analysis.specific_improvements,
        traditional_correction: `질문 적용\n${analysis.contextual_meaning}\n\n정통 의미\n${analysis.traditional_core}\n\n상징 근거\n${analysis.symbol_notes.join(" ")}`,
        sample_answer: analysis.sample_answer_draft,
        model_answer: analysis.model_answer_draft,
        missed_key_points: analysis.missed_key_points,
        differences: analysis.difference_notes,
        wrong_note: analysis.correction_note,
        next_reading_tip: analysis.feedback_focus,
        promptVersion: FEEDBACK_PROMPT_VERSION,
      },
      null,
      2,
    ),
  ].join("\n");
}

const categoryLabel: Record<string, string> = {
  love: "연애",
  reunion: "재회",
  crush: "짝사랑",
  career: "직업",
  business: "사업",
  money: "금전",
  health: "건강",
  relationship: "인간관계",
  family: "가족",
  path: "진로",
  job_change: "이직",
  exam: "시험",
  general: "오늘의 운세",
};

function getContextText({ card, question }: Pick<EvaluationInput, "card" | "question">) {
  const contexts = card.contexts;
  if (!contexts) return "";

  if (
    question.category === "love" ||
    question.category === "reunion" ||
    question.category === "career" ||
    question.category === "business" ||
    question.category === "money" ||
    question.category === "health"
  ) {
    return contexts[question.category]?.[question.orientation] ?? "";
  }

  return "";
}
