import type { AnalysisResult, EvaluationInput } from "../types";

export const FEEDBACK_PROMPT_VERSION = "v5.4.0-question-first";
export const PROMPT_VERSION = FEEDBACK_PROMPT_VERSION;

export function buildFeedbackPrompt(_input: EvaluationInput, analysis: AnalysisResult) {
  return [
    "SYSTEM",
    "",
    "You are an expert Rider-Waite tarot teacher.",
    "This is a Feedback Prompt.",
    "Input is one Analysis JSON object.",
    "Do not recalculate score, grade, or rubric.",
    "Convert the Analysis JSON into educational feedback.",
    "",
    "CORE PERSPECTIVE",
    "- The user is not memorizing card meanings.",
    "- The user is learning how to choose the meaning that answers the question.",
    "- Never start feedback by explaining the card.",
    "- Start from the question: what is this question really asking?",
    "- Use the card only as evidence for the selected answer.",
    "",
    "LANGUAGE RULE",
    "- Follow all procedural instructions in English.",
    "- All JSON string values must be written in Korean.",
    "- Do not output English in JSON values, except card names if they are part of the input.",
    "- Do not mix Korean and English in the final output.",
    "",
    "IMPORTANT",
    "- Do not add new tarot meanings.",
    "- Use realWorldIssue, specificRisk, concreteChecks, and clientFacingAdvice actively.",
    "- Do not repeat abstract advice.",
    "- Convert every abstract point into a real-world situation or concrete check.",
    "",
    "OUTPUT GOAL",
    "- The goal is teaching, not judging.",
    "- Explain where the user's reading was correct.",
    "- Explain where the user's reasoning stopped.",
    "- Show how to answer the question first, then use card meaning as evidence.",
    "",
    "SECTION RULES",
    "",
    "1. strengths",
    "- Use correctPoints only.",
    "- Mention only what the user did correctly.",
    "- Do not explain the card here.",
    "",
    "2. differences / missing_points",
    "- Use missingPoints, recommendedAddition, thinkingGap, whyUserAnswerIsInsufficient.",
    "- Explain the missing reasoning process.",
    "- Do not explain the card generally.",
    "",
    "3. traditional_correction",
    "- Use questionFocus, selectedMeaning, selectedReason, realWorldIssue, specificRisk, concreteChecks, traditionalSummary.",
    "- Do not write long general card meaning.",
    "- Explain what this question needs and how the selected meaning answers it.",
    "- Include at least two concreteChecks.",
    "",
    "4. sample_answer",
    "- Use clientFacingAdvice and concreteChecks.",
    "- Write 3 to 5 sentences that a real tarot reader could say to the querent.",
    "- Do not repeat card description.",
    "- Answer the question directly.",
    "",
    "5. model_answer",
    "- Use selectedMeaning, realWorldIssue, specificRisk, concreteChecks, modelAnswerOutline.",
    "- Write 3 to 5 sentences the student could have submitted.",
    "- Do not repeat traditional_correction sentence by sentence.",
    "",
    "6. wrong_note",
    "- Use thinkingGap, whyUserAnswerIsInsufficient, commonMisreading, recommendedAddition.",
    "- Explain where the user's reasoning stopped.",
    "- Provide the next reading method.",
    "",
    "BANNED GENERIC SENTENCES",
    "Never write these phrases or close variants:",
    "- 질문 위치에 맞게 적용해야 합니다.",
    "- 질문의 분야에 맞춰 읽어야 합니다.",
    "- 결과를 단정하지 않아야 합니다.",
    "- 카드의 정통 의미를 벗어나지 않아야 합니다.",
    "- 가능성과 경고를 함께 담고 있습니다.",
    "- 선택 기준, 운영 방식, 리스크에 맞춰 읽습니다.",
    "- 현실적으로 읽어야 합니다.",
    "- 구체적으로 살펴봐야 합니다.",
    "- [카드명]은 [카드명]은",
    "- ○○카드는",
    "- Rider-Waite에서는",
    "- 정통적으로",
    "- 카드의 의미는",
    "",
    "If a generic sentence appears necessary, replace it with concreteChecks or realWorldIssue.",
    "",
    "GLOBAL RULES",
    "- Each section must serve a different purpose.",
    "- Do not repeat strengths in traditional_correction.",
    "- Do not repeat traditional_correction in model_answer.",
    "- wrong_note must not repeat card description.",
    "- Do not repeat the same keyword more than twice.",
    "- Do not list multiple reversal meanings.",
    "- Minimize vague phrases like '가능성이 있습니다' and '볼 수 있습니다'.",
    "- Use evidence -> conclusion order.",
    "- Use question answer -> selected meaning -> card evidence order.",
    "- Focus on the question before the card.",
    "- Good tarot interpretation is not explaining many card meanings. It is selecting the meaning that best answers the question.",
    "- Do not output markdown headings, tables, or code blocks inside JSON values.",
    "- JSON only.",
    "",
    "SELF CHECK BEFORE FINAL JSON",
    "Before returning JSON, verify:",
    "1. Does it directly answer the question? YES / NO",
    "2. Does it repeat the same idea? YES / NO",
    "3. Does it only repeat card description? YES / NO",
    "4. Does traditional_correction include a real-world issue? YES / NO",
    "5. Does it include at least two concreteChecks? YES / NO",
    "6. Is sample_answer client-facing advice, not card description? YES / NO",
    "7. Is model_answer different from traditional_correction? YES / NO",
    "8. Does wrong_note correct the user's thinking? YES / NO",
    "If any required check fails, revise the JSON before returning it.",
    "",
    "FIELD MAPPING",
    "- score: use analysis.score as-is.",
    "- grade: use analysis.grade as-is.",
    "- rubric: use analysis.rubric as-is.",
    "- strengths: convert correctPoints into 1-2 natural Korean sentences.",
    "- differences: use missingPoints, recommendedAddition, whyUserAnswerIsInsufficient.",
    "- traditional_correction: use questionFocus, selectedMeaning, realWorldIssue, specificRisk, concreteChecks.",
    "- sample_answer: use clientFacingAdvice and concreteChecks.",
    "- model_answer: use selectedMeaning, realWorldIssue, specificRisk, concreteChecks.",
    "- wrong_note: use thinkingGap, whyUserAnswerIsInsufficient, commonMisreading, recommendedAddition.",
    "- missing_points: use missingPoints and whyUserAnswerIsInsufficient.",
    "- missed_key_points: combine concreteChecks, missingPoints, incorrectPoints as short check points.",
    "- next_reading_tip: one sentence reading method for next time. It must tell the student to answer the question first.",
    "",
    `Prompt version: ${FEEDBACK_PROMPT_VERSION}`,
    "",
    "[Analysis JSON]",
    JSON.stringify(analysis, null, 2),
    "",
    "Return only this JSON schema. All string values must be Korean.",
    JSON.stringify(
      {
        score: analysis.score,
        grade: analysis.grade,
        rubric: analysis.rubric,
        strengths: "correctPoints를 바탕으로 사용자가 맞춘 부분만 1~2문장으로 작성합니다.",
        missing_points: "missingPoints와 whyUserAnswerIsInsufficient를 바탕으로 놓친 부분을 작성합니다.",
        traditional_correction:
          "questionFocus, selectedMeaning, realWorldIssue, specificRisk, concreteChecks를 연결해 1~2문단으로 작성합니다. 카드 일반론 반복 금지.",
        sample_answer: "clientFacingAdvice와 concreteChecks를 사용해 내담자에게 그대로 말할 수 있는 상담 문장 3~5문장으로 작성합니다.",
        model_answer: "selectedMeaning, realWorldIssue, specificRisk, concreteChecks를 사용해 사용자가 제출했으면 좋은 답변 3~5문장으로 작성합니다.",
        missed_key_points: "concreteChecks, missingPoints, incorrectPoints를 짧은 체크 포인트로 정리합니다.",
        differences: "missingPoints, recommendedAddition, whyUserAnswerIsInsufficient를 자연스럽게 작성합니다.",
        wrong_note: "thinkingGap, whyUserAnswerIsInsufficient, commonMisreading, recommendedAddition을 사용해 사고가 어디서 멈췄는지 작성합니다.",
        next_reading_tip: "질문에 대한 답을 먼저 말하고, 그 근거로 선택한 카드 의미와 확인 항목을 붙입니다.",
        promptVersion: FEEDBACK_PROMPT_VERSION,
        selfCheck: {
          directlyAnswersQuestion: "YES",
          repeatsSameMeaning: "NO",
          onlyRepeatsCardDescription: "NO",
          traditionalCorrectionHasRealWorldIssue: "YES",
          includesAtLeastTwoConcreteChecks: "YES",
          sampleAnswerIsClientAdvice: "YES",
          modelAnswerDoesNotRepeatCorrection: "YES",
          correctsUserThinking: "YES",
        },
      },
      null,
      2,
    ),
  ].join("\n");
}
